// Why I Don't Think Blockchain is the Future
#import "/template-en.typ": doc-template

#doc-template(
title: "Why I Don't Think Blockchain is the Future",
date: "July 13, 2018",
body: [

First, I must admit this title is quite cliché, but for a moment, I couldn't think of a better one. Blockchain or cryptocurrency was originally just a niche hobby. However, starting from 2016, this niche field began to surge, with various capitals pouring in, becoming the biggest trend of 2017. Countless people began to preach that this is the next internet, the future of mankind, and so on. Coupled with the myths of instant wealth created by the skyrocketing prices of cryptocurrencies, such publicity became even more inflammatory. However, as the title suggests, I firmly believe that blockchain will not be the future, and I will summarize my reasons below.

Let's start with the most basic application of blockchain: cryptocurrency. Cryptocurrency is a remarkable attempt; it gives us for the first time a means of payment through the internet that does not rely on any bank or company. However, its limitations are beyond doubt. A system that can only complete a few transactions per second globally is destined to be unusable, and even with measures like micropayment channels or the Lightning Network, the effect remains very limited. Moreover, due to the inherent constraints of P2P networks, it is almost impossible to have large-scale expansion. Existing technical means can improve the anonymity and decentralization of cryptocurrencies, but the network structure itself dictates that further increasing transaction frequency is impossible.

For financial applications, the most important thing is trust. To achieve trust under decentralized conditions, Bitcoin chooses to let everyone store a copy of transaction data, while ensuring the validity of transaction data at the cost of wasting energy; this is an inevitable compromise. Therefore, many blockchain currency projects claiming higher transaction frequencies often do so at the cost of centralization. This runs counter to the original goal of cryptocurrency: if one doesn't care about centralization, the better choice is obviously a bank. The trust system built by banks has been running stably for hundreds of years and works very well. In contrast, those centralized blockchain projects have no advantage whatsoever.

The second application scenario many promote for blockchain is clearing and settlement between different institutions. But this is truly absurd. To perform clearing and settlement between different institutions, a jointly operated ordinary software platform is sufficient. As for those flashy consensus mechanisms, such as the famous BFT, their actual role is quite limited. Imagine if a property dispute occurs between companies during clearing and settlement; in the end, they still have to meet in court, still requiring the involvement of legal and financial personnel. Therefore, the labor costs that blockchain can reduce can also be achieved with ordinary financial software. Furthermore, blockchain requires additional software development costs.

Some have envisioned a more distant prospect: with blockchain, if there are good protocols and mechanisms, everything will be code; we will not need lawyers or accountants, and the entire social structure will be overturned. But in this parallel universe of ours, this is certainly unattainable. And even if it were achieved, there's no way to guarantee the security of the code; by then, crackers could do as they please, just like the powerful or wealthy in our era. However, I am quite looking forward to cyberpunk and dystopian novels/movies/animations inspired by this.

As for other applications, such as traceability or the health industry (mostly for medical record storage), blockchain is even less necessary. Software like Git has long provided these functions, so why go to all that trouble? These applications give me the feeling of: "When you have a hammer, everything looks like a nail."

Moreover, the term "Internet of Value" is not a new concept in itself. We use Alipay every day, banks have opened online banking services, and we can tip our favorite creators on Patreon. On the internet, value has long been interconnected. This is also the fundamental difference between the blockchain bubble and the previous internet bubble: blockchain has not brought new functions like online shopping; it only adds decentralization and anonymity attributes to the interconnection of value on the internet. However, except for hackers and cyberpunks who value privacy extremely highly, the general public cares more about user experience, and in this regard, blockchain applications will never catch up with centralized trust applications like Alipay and PayPal. Furthermore, blockchain applications haven't provided any new functions. Besides, banks and companies like Alibaba have already accumulated enough trust, and trust is very difficult to tear down and rebuild. Centralization is indeed the trend of internet development: cloud storage has replaced BT downloads, and blog platforms have replaced personal homepages. Although I personally am not happy to see centralization, it is a fact. The limitations and difficulty of decentralizing property and trust are also far higher than those of decentralizing information.

In summary, I have enough reasons to believe that blockchain, something born from anarchism, will return to its original place; it will not be our future. This wave of blockchain will eventually die down just like the hype around the Internet of Things and Virtual Reality.

Of course, the future is hard to predict; the cautionary tale of "who would want a computer at home" is right there.

])
