// Talking About Disordered Timelines
#import "/template-en.typ": doc-template

#doc-template(
title: "Talking About Disordered Timelines",
date: "September 26, 2017",
body: [

The biggest difference between social networks and other early internet applications like BBS is the "timeline" mechanism. Early social network timeline mechanisms were very simple: they just arranged the status updates of friends in chronological order. Today, many social networks still maintain this mechanism, such as Tencent's Qzone and WeChat Moments. This chronological timeline is simple and clear; when a user scrolls to a certain point in time, they know they have seen all the latest updates and can stop.

However, a new timeline mechanism has been born: the disordered timeline. I must explain that the term "disordered timeline" is not a widely accepted name, but a term I coined to describe this type of timeline mechanism.

I haven't found an exact record of the specific date the disordered timeline was invented. In my impression, the first to use this mechanism seemed to be Facebook. Facebook used an algorithm called EdgeRank in its timeline (or News Feed). In 2010, Facebook released a simplified version of EdgeRank, which, from its name, should be a tribute to Google's PageRank algorithm. However, EdgeRank doesn't seem to be as complex as PageRank, but since it's just a simplified version, the real situation remains unknown. This simplified version of the EdgeRank algorithm uses three parameters: affinity, weight, and time decay. Based on these three parameters, Facebook scores the status updates of a user's friends and arranges these statuses. This bears some resemblance to Hacker News's ranking algorithm. I also found a small website dedicated to #link("http://edgerank.net/", "introducing EdgeRank"), whose homepage illustration has an industrial revolution style.

Today, however, Facebook no longer uses the EdgeRank algorithm, but has adopted more complex machine learning algorithms. Compared to EdgeRank, the new machine learning algorithms have more parameters, but the timeline mechanism is generally similar. Meanwhile, Twitter has also begun to adopt a similar mechanism. Starting about a year ago, the tweets on a Twitter user's timeline are no longer arranged completely chronologically as they were before; at the same time, the algorithm automatically selects and displays some information liked by other users on the timeline. However, compared to Facebook, Twitter's timeline mechanism is still relatively orderly.

Compared to traditional timeline mechanisms, this disordered timeline naturally has some benefits. in traditional social networks, if a user follows too many people, the timeline becomes overcrowded, leaving one overwhelmed in a sea of information. Algorithms like EdgeRank help users make choices, saving them time in a sense. It seems the disordered timeline mechanism is advanced and considers the user's interests, but in fact, it is a form of tyranny over users because users lose their freedom; all these social networks that use disordered timelines do so instead of letting users choose freely. This means that disordered timelines are imposed on users.

This disordered timeline tyranny has many harms. First, it indulges users in following other users without restraint. This increases user stickiness in a sense, but it also makes the scale of social networks uncontrollable. If a traditional timeline is used, when the number of followed people is too large and the information is overcrowded, we naturally think of streamlining the number of followed users. But with algorithm recommendations, this concern no longer exists, and there is no longer an upper limit on the number of follows. Second, users no longer have the freedom to choose what content they see; the algorithm decides what users see or don't see today. Perhaps the algorithm itself is impartial, but it doesn't run on our own computers; it runs on servers. Therefore, its running results can be manipulated by server administrators. So, in the end, it evolves into Silicon Valley giants deciding what users should or shouldn't see. The decentralization of the internet brought media power to everyone. However, the increasing centralization of the internet has returned media power to a few, which can only be called a regression. This also seems to explain why Trump's base is not Facebook, but Twitter, which has a more traditional timeline mechanism. Human thought activities will inevitably be influenced by the outside world, and this power to manipulate people's minds is very worthy of vigilance.

The domestic internet is naturally no exception. Zhihu and Weibo have long introduced such algorithm-recommended disordered timelines. These mechanisms have given these websites the right to limit traffic and promote content at will, and have also given their business operations more space. Every day, countless data packets are sent globally from machines that glow green and hum. These data packets may be the running result of a carefully tuned artificial neural network, or they may directly be the clever design of some person behind the scenes. Some people like this screening, and some don't. It's just that those who don't like it are powerless to change it and have to choose to escape.

])
